#!/usr/bin/env python3
import sys
import json

inp = json.load(sys.stdin)
f = inp.get('tool_input', {}).get('file_path', '')

if f.endswith('app.yaml') and 'template' not in f:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": "Edit app.template.yaml instead - app.yaml is auto-generated by make render-app-config"
        }
    }))
