import type { QueryField, QueryRegistry, QueryValueType } from '@connectio/shared-reporting';
import { endpoint, fields as selectFields, params, postQuery, widgetCompatibility } from './common';

/**
 * Creates a POH-specific field definition.
 *
 * @param path - Dot-path in the response payload.
 * @param label - Human-readable field label.
 * @param type - Expected value type.
 * @param semantic - Optional semantic hint for mapping defaults.
 * @returns Query field metadata for the registry.
 */
function pohField(
  path: string,
  label: string,
  type: QueryValueType,
  semantic?: QueryField['semantic'],
): QueryField {
  return { path, label, type, semantic };
}

const pohWindowParams = params('plant_id', 'date_from', 'date_to', 'timezone');
const pohOrderParams = params(
  'plant_id',
  'date_from',
  'date_to',
  'timezone',
  'material_id',
  'resource_id',
  'line_id',
  'process_order_id',
);

const pohSummaryFields: QueryField[] = [
  pohField('order_count', 'Order count', 'number', 'count'),
  pohField('released_order_count', 'Released order count', 'number', 'count'),
  pohField('confirmed_order_count', 'Confirmed order count', 'number', 'count'),
  pohField('late_order_count', 'Late order count', 'number', 'count'),
  pohField('avg_cycle_time_hours', 'Average cycle time (hours)', 'number', 'duration'),
  pohField('schedule_adherence_pct', 'Schedule adherence %', 'number', 'percentage'),
  pohField('total_planned_qty', 'Total planned quantity', 'number'),
  pohField('total_confirmed_qty', 'Total confirmed quantity', 'number'),
  pohField('yield_pct', 'Yield %', 'number', 'percentage'),
  pohField('scrap_qty', 'Scrap quantity', 'number'),
  ...selectFields('plant_id', 'material_id', 'material_description', 'batch_id', 'posting_date', 'process_order_id', 'status', 'uom'),
  pohField('resource_id', 'Resource', 'string'),
  pohField('resource_name', 'Resource name', 'string'),
  pohField('confirmation_date', 'Confirmation date', 'date'),
  pohField('daily_history', 'Daily history', 'array', 'timeseries'),
  pohField('categories', 'Categories', 'array'),
  pohField('series', 'Series', 'array'),
  pohField('rows', 'Rows', 'array'),
];

const pohSummarySample = {
  order_count: 184,
  released_order_count: 176,
  confirmed_order_count: 169,
  late_order_count: 12,
  avg_cycle_time_hours: 18.6,
  schedule_adherence_pct: 92.4,
  total_planned_qty: 48250,
  total_confirmed_qty: 47180,
  yield_pct: 97.8,
  scrap_qty: 410,
  plant_id: 'C061',
  process_order_id: '000147845120',
  material_id: '000000000020052009',
  material_description: 'Breaded fillet strips 5kg',
  batch_id: '0008602411',
  posting_date: '2026-05-12',
  confirmation_date: '2026-05-12',
  resource_id: 'LINE-07',
  resource_name: 'Cook Line 07',
  status: 'Confirmed',
  uom: 'KG',
  daily_history: [
    { label: 'Mon', value: 89.6 },
    { label: 'Tue', value: 91.8 },
    { label: 'Wed', value: 92.4 },
  ],
  categories: ['Line 05', 'Line 07', 'Line 09'],
  series: [{ name: 'OEE %', data: [88.1, 92.4, 90.3] }],
  rows: [
    {
      process_order_id: '000147845120',
      material_id: '000000000020052009',
      material_description: 'Breaded fillet strips 5kg',
      resource_id: 'LINE-07',
      resource_name: 'Cook Line 07',
      status: 'Confirmed',
      total_planned_qty: 4800,
      total_confirmed_qty: 4710,
      yield_pct: 98.1,
      confirmation_date: '2026-05-12',
    },
  ],
};

/**
 * Process Order History query definitions for the platform dashboard builder.
 */
export const pohQueries: QueryRegistry = {
  'poh.oeeAnalytics': postQuery({
    key: 'poh.oeeAnalytics',
    label: 'Process Order OEE Analytics',
    description: 'Overall Equipment Effectiveness by line with top-line KPIs and daily history.',
    endpoint: endpoint('poh', 'oee/analytics'),
    compatibleWidgets: widgetCompatibility.kpiTrendBar,
    params: pohWindowParams,
    fields: [
      pohField('value', 'Top-line OEE %', 'number', 'percentage'),
      pohField('delta', 'OEE delta', 'string'),
      pohField('subtext', 'KPI subtext', 'string'),
      pohField('progressBar', 'OEE progress bar', 'number', 'percentage'),
      pohField('lines.0.avg_oee_pct', 'Average OEE % (top line)', 'number', 'percentage'),
      pohField('lines.0.avg_availability_pct', 'Availability % (top line)', 'number', 'percentage'),
      pohField('lines.0.avg_performance_pct', 'Performance % (top line)', 'number', 'percentage'),
      pohField('lines.0.avg_quality_pct', 'Quality % (top line)', 'number', 'percentage'),
      pohField('lines.0.daily_history', 'Daily OEE history (top line)', 'array', 'timeseries'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
      pohField('lines', 'All line statistics', 'array'),
    ],
    sampleResponse: {
      value: 92.4,
      unit: '%',
      delta: '+1.8%',
      trend: 'up',
      subtext: 'vs previous 7 days',
      progressBar: 92.4,
      categories: ['Line 05', 'Line 07', 'Line 09'],
      series: [{ name: 'OEE %', data: [88.1, 92.4, 90.3] }],
      rows: [
        { line_id: 'LINE-05', avg_oee_pct: 88.1, avg_availability_pct: 92.2, avg_performance_pct: 89.9, avg_quality_pct: 95.8 },
        { line_id: 'LINE-07', avg_oee_pct: 92.4, avg_availability_pct: 95.1, avg_performance_pct: 94.2, avg_quality_pct: 97.5 },
      ],
      lines: [
        {
          line_id: 'LINE-07',
          line_name: 'Cook Line 07',
          avg_oee_pct: 92.4,
          avg_availability_pct: 95.1,
          avg_performance_pct: 94.2,
          avg_quality_pct: 97.5,
          daily_history: [
            { label: 'Mon', value: 89.6 },
            { label: 'Tue', value: 91.8 },
            { label: 'Wed', value: 92.4 },
          ],
        },
      ],
    },
  }),
  'poh.orderSummary': postQuery({
    key: 'poh.orderSummary',
    label: 'Process Order Summary',
    description: 'Top-line process order counts, quantities, and yield over the selected production window.',
    endpoint: endpoint('poh', 'order-summary'),
    compatibleWidgets: widgetCompatibility.kpiBarTable,
    params: pohOrderParams,
    fields: pohSummaryFields,
    sampleResponse: pohSummarySample,
  }),
  'poh.orderTimeline': postQuery({
    key: 'poh.orderTimeline',
    label: 'Order Timeline',
    description: 'Chronological order completion and cycle-time history for the selected production scope.',
    endpoint: endpoint('poh', 'order-timeline'),
    compatibleWidgets: widgetCompatibility.trendTable,
    params: pohOrderParams,
    fields: [
      pohField('points', 'Timeline points', 'array', 'timeseries'),
      pohField('daily_history', 'Daily history', 'array', 'timeseries'),
      pohField('rows', 'Rows', 'array'),
      ...pohSummaryFields,
    ],
    sampleResponse: {
      points: [
        { label: '2026-05-08', value: 21.4 },
        { label: '2026-05-09', value: 20.7 },
        { label: '2026-05-10', value: 18.9 },
      ],
      daily_history: [
        { label: '2026-05-08', value: 21.4 },
        { label: '2026-05-09', value: 20.7 },
        { label: '2026-05-10', value: 18.9 },
      ],
      rows: [
        {
          process_order_id: '000147845120',
          status: 'Confirmed',
          posting_date: '2026-05-10',
          confirmation_date: '2026-05-10',
          avg_cycle_time_hours: 18.9,
          resource_id: 'LINE-07',
          resource_name: 'Cook Line 07',
        },
      ],
      ...pohSummarySample,
    },
  }),
  'poh.productionTrend': postQuery({
    key: 'poh.productionTrend',
    label: 'Production Trend',
    description: 'Planned versus confirmed production quantities trended across the selected time window.',
    endpoint: endpoint('poh', 'production-trend'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: pohOrderParams,
    fields: [
      pohField('value', 'Confirmed quantity', 'number'),
      pohField('delta', 'Confirmed quantity delta', 'string'),
      pohField('subtext', 'KPI subtext', 'string'),
      pohField('points', 'Production points', 'array', 'timeseries'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
      ...pohSummaryFields,
    ],
    sampleResponse: {
      value: 47180,
      unit: 'KG',
      delta: '+3.4%',
      trend: 'up',
      subtext: 'confirmed vs previous 7 days',
      points: [
        { label: 'Mon', value: 15400 },
        { label: 'Tue', value: 16080 },
        { label: 'Wed', value: 15700 },
      ],
      categories: ['Mon', 'Tue', 'Wed'],
      series: [
        { name: 'Confirmed qty', data: [15400, 16080, 15700] },
        { name: 'Planned qty', data: [15000, 16250, 17000] },
      ],
      rows: pohSummarySample.rows,
      ...pohSummarySample,
    },
  }),
  'poh.productionByMaterial': postQuery({
    key: 'poh.productionByMaterial',
    label: 'Production by Material',
    description: 'Produced quantity and yield by material for Pareto, bar, and tabular analysis.',
    endpoint: endpoint('poh', 'production-by-material'),
    compatibleWidgets: widgetCompatibility.barParetoTable,
    params: params('plant_id', 'date_from', 'date_to', 'timezone', 'material_id'),
    fields: [
      ...selectFields('material_id', 'material_description', 'uom'),
      pohField('yield_pct', 'Yield %', 'number', 'percentage'),
      pohField('total_confirmed_qty', 'Confirmed quantity', 'number'),
      pohField('scrap_qty', 'Scrap quantity', 'number'),
      pohField('items', 'Pareto items', 'array'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
    ],
    sampleResponse: {
      categories: ['Breaded strips 5kg', 'Chicken bites 4kg', 'Nuggets 10kg'],
      series: [{ name: 'Confirmed qty', data: [18600, 14500, 14080] }],
      items: [
        { label: 'Breaded strips 5kg', value: 18600 },
        { label: 'Chicken bites 4kg', value: 14500 },
      ],
      rows: [
        {
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          total_confirmed_qty: 18600,
          yield_pct: 98.1,
          scrap_qty: 120,
          uom: 'KG',
        },
      ],
    },
  }),
  'poh.resourcePerformance': postQuery({
    key: 'poh.resourcePerformance',
    label: 'Resource Performance',
    description: 'Compares throughput, cycle time, and yield across resources and lines.',
    endpoint: endpoint('poh', 'resource-performance'),
    compatibleWidgets: widgetCompatibility.kpiBarTable,
    params: params('plant_id', 'date_from', 'date_to', 'timezone', 'resource_id', 'line_id'),
    fields: [
      pohField('value', 'Top resource throughput', 'number'),
      pohField('subtext', 'KPI subtext', 'string'),
      pohField('resource_id', 'Resource', 'string'),
      pohField('resource_name', 'Resource name', 'string'),
      pohField('avg_cycle_time_hours', 'Average cycle time (hours)', 'number', 'duration'),
      pohField('yield_pct', 'Yield %', 'number', 'percentage'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
    ],
    sampleResponse: {
      value: 18500,
      unit: 'KG',
      subtext: 'highest confirmed throughput',
      resource_id: 'LINE-07',
      resource_name: 'Cook Line 07',
      avg_cycle_time_hours: 18.9,
      yield_pct: 98.1,
      categories: ['Cook Line 05', 'Cook Line 07', 'Cook Line 09'],
      series: [{ name: 'Confirmed qty', data: [17320, 18500, 16360] }],
      rows: [
        {
          resource_id: 'LINE-07',
          resource_name: 'Cook Line 07',
          total_confirmed_qty: 18500,
          avg_cycle_time_hours: 18.9,
          yield_pct: 98.1,
        },
      ],
    },
  }),
  'poh.scheduleAdherence': postQuery({
    key: 'poh.scheduleAdherence',
    label: 'Schedule Adherence',
    description: 'Tracks on-time completion rates and late-order counts across the selected production scope.',
    endpoint: endpoint('poh', 'schedule-adherence'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: pohOrderParams,
    fields: [
      pohField('value', 'Schedule adherence %', 'number', 'percentage'),
      pohField('delta', 'Schedule adherence delta', 'string'),
      pohField('subtext', 'KPI subtext', 'string'),
      pohField('progressBar', 'Progress bar', 'number', 'percentage'),
      pohField('points', 'Schedule adherence points', 'array', 'timeseries'),
      ...pohSummaryFields,
    ],
    sampleResponse: {
      value: 92.4,
      unit: '%',
      delta: '+0.9%',
      trend: 'up',
      subtext: 'on-time completion rate',
      progressBar: 92.4,
      points: [
        { label: 'Mon', value: 90.2 },
        { label: 'Tue', value: 91.6 },
        { label: 'Wed', value: 92.4 },
      ],
      ...pohSummarySample,
    },
  }),
  'poh.orderStatusBreakdown': postQuery({
    key: 'poh.orderStatusBreakdown',
    label: 'Order Status Breakdown',
    description: 'Breaks down order volume by operational status for Pareto, bar, and table views.',
    endpoint: endpoint('poh', 'order-status-breakdown'),
    compatibleWidgets: widgetCompatibility.barParetoTable,
    params: pohOrderParams,
    fields: [
      ...selectFields('status'),
      pohField('items', 'Pareto items', 'array'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
      pohField('order_count', 'Order count', 'number', 'count'),
    ],
    sampleResponse: {
      categories: ['Confirmed', 'Released', 'In Process', 'Late'],
      series: [{ name: 'Orders', data: [169, 176, 8, 12] }],
      items: [
        { label: 'Confirmed', value: 169 },
        { label: 'Released', value: 176 },
        { label: 'Late', value: 12 },
      ],
      rows: [
        { status: 'Confirmed', order_count: 169 },
        { status: 'Released', order_count: 176 },
        { status: 'Late', order_count: 12 },
      ],
    },
  }),
  'poh.confirmationTrend': postQuery({
    key: 'poh.confirmationTrend',
    label: 'Confirmation Trend',
    description: 'Trends order confirmations and confirmed quantity across the selected date range.',
    endpoint: endpoint('poh', 'confirmation-trend'),
    compatibleWidgets: widgetCompatibility.trendBarTable,
    params: pohOrderParams,
    fields: [
      pohField('points', 'Confirmation points', 'array', 'timeseries'),
      pohField('categories', 'Categories', 'array'),
      pohField('series', 'Series', 'array'),
      pohField('rows', 'Rows', 'array'),
      pohField('confirmed_order_count', 'Confirmed order count', 'number', 'count'),
      pohField('total_confirmed_qty', 'Confirmed quantity', 'number'),
      pohField('confirmation_date', 'Confirmation date', 'date'),
      ...selectFields('process_order_id', 'material_id', 'material_description', 'uom'),
    ],
    sampleResponse: {
      points: [
        { label: 'Mon', value: 54 },
        { label: 'Tue', value: 58 },
        { label: 'Wed', value: 57 },
      ],
      categories: ['Mon', 'Tue', 'Wed'],
      series: [{ name: 'Confirmed orders', data: [54, 58, 57] }],
      rows: [
        {
          process_order_id: '000147845120',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          total_confirmed_qty: 4710,
          confirmed_order_count: 1,
          confirmation_date: '2026-05-10',
          uom: 'KG',
        },
      ],
    },
  }),
};
