import type { QueryField, QueryRegistry, QueryValueType } from '@connectio/shared-reporting';
import { endpoint, fields as selectFields, params, postQuery, widgetCompatibility } from './common';

/**
 * Creates a warehouse-management field definition.
 *
 * @param path - Dot-path in the response payload.
 * @param label - Human-readable field label.
 * @param type - Expected value type.
 * @param semantic - Optional semantic hint for mapping defaults.
 * @returns Query field metadata for the registry.
 */
function wmField(
  path: string,
  label: string,
  type: QueryValueType,
  semantic?: QueryField['semantic'],
): QueryField {
  return { path, label, type, semantic };
}

const wmParams = params(
  'plant_id',
  'date_from',
  'date_to',
  'material_id',
  'batch_id',
  'process_order_id',
  'warehouse_number',
  'storage_type',
  'storage_bin',
);

/**
 * Warehouse-management query definitions for the platform dashboard builder.
 */
export const wmQueries: QueryRegistry = {
  'wm.stagingOverview': postQuery({
    key: 'wm.stagingOverview',
    label: 'WM Staging Overview',
    description: 'High-level staging queue health across open, staged, and ageing supply positions.',
    endpoint: endpoint('wm', 'staging-overview'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Staged quantity', 'number'),
      wmField('delta', 'Staged quantity delta', 'string'),
      wmField('subtext', 'KPI subtext', 'string'),
      wmField('staged_qty', 'Staged quantity', 'number'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('age_minutes', 'Age (minutes)', 'number', 'duration'),
      wmField('points', 'Points', 'array', 'timeseries'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
    ],
    sampleResponse: {
      value: 4820,
      unit: 'KG',
      delta: '+4.2%',
      trend: 'up',
      subtext: 'staged for next 8 hours',
      staged_qty: 4820,
      open_qty: 910,
      age_minutes: 42,
      points: [
        { label: '06:00', value: 3800 },
        { label: '08:00', value: 4210 },
        { label: '10:00', value: 4820 },
      ],
      categories: ['Open', 'Staged', 'Late'],
      series: [{ name: 'Queue qty', data: [910, 4820, 230] }],
      rows: [
        {
          warehouse_number: '061',
          process_order_id: '000147845120',
          staged_qty: 1820,
          open_qty: 240,
          age_minutes: 42,
        },
      ],
    },
  }),
  'wm.transferRequirements': postQuery({
    key: 'wm.transferRequirements',
    label: 'Transfer Requirements',
    description: 'Open transfer requirements by material, priority, and source staging demand.',
    endpoint: endpoint('wm', 'transfer-requirements'),
    compatibleWidgets: widgetCompatibility.kpiBarParetoTable,
    params: wmParams,
    fields: [
      wmField('value', 'Requirement count', 'number', 'count'),
      wmField('required_qty', 'Required quantity', 'number'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('priority', 'Priority', 'string', 'status'),
      wmField('tr_number', 'Transfer requirement', 'string'),
      wmField('items', 'Pareto items', 'array'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
      ...selectFields('material_id', 'material_description', 'batch_id', 'process_order_id', 'uom'),
    ],
    sampleResponse: {
      value: 18,
      required_qty: 6150,
      open_qty: 1880,
      priority: 'High',
      categories: ['Protein prep', 'Coating', 'Packaging'],
      series: [{ name: 'Open qty', data: [720, 610, 550] }],
      items: [
        { label: 'Protein prep', value: 720 },
        { label: 'Coating', value: 610 },
      ],
      rows: [
        {
          tr_number: 'TR-884120',
          process_order_id: '000147845120',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          required_qty: 920,
          open_qty: 240,
          priority: 'High',
          uom: 'KG',
        },
      ],
    },
  }),
  'wm.transferOrders': postQuery({
    key: 'wm.transferOrders',
    label: 'Transfer Orders',
    description: 'Open transfer orders with picked, staged, and remaining execution quantities.',
    endpoint: endpoint('wm', 'transfer-orders'),
    compatibleWidgets: widgetCompatibility.kpiBarParetoTable,
    params: wmParams,
    fields: [
      wmField('value', 'Transfer order count', 'number', 'count'),
      wmField('picked_qty', 'Picked quantity', 'number'),
      wmField('staged_qty', 'Staged quantity', 'number'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('to_number', 'Transfer order', 'string'),
      wmField('priority', 'Priority', 'string', 'status'),
      wmField('items', 'Pareto items', 'array'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
    ],
    sampleResponse: {
      value: 11,
      picked_qty: 3920,
      staged_qty: 3510,
      open_qty: 410,
      categories: ['Released', 'Picked', 'Staged'],
      series: [{ name: 'TO qty', data: [410, 3920, 3510] }],
      items: [
        { label: 'Released', value: 410 },
        { label: 'Picked', value: 3920 },
        { label: 'Staged', value: 3510 },
      ],
      rows: [
        {
          to_number: 'TO-554210',
          process_order_id: '000147845120',
          picked_qty: 820,
          staged_qty: 760,
          open_qty: 60,
          priority: 'High',
        },
      ],
    },
  }),
  'wm.productionSupplyQueue': postQuery({
    key: 'wm.productionSupplyQueue',
    label: 'Production Supply Queue',
    description: 'Queues production supply tasks by order, due time, and open supply quantity.',
    endpoint: endpoint('wm', 'production-supply-queue'),
    compatibleWidgets: widgetCompatibility.kpiBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Open supply quantity', 'number'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('due_time', 'Due time', 'string'),
      wmField('priority', 'Priority', 'string', 'status'),
      wmField('rows', 'Rows', 'array'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      ...selectFields('process_order_id', 'material_id', 'material_description', 'batch_id', 'uom'),
    ],
    sampleResponse: {
      value: 910,
      open_qty: 910,
      due_time: '2026-05-12T12:30:00Z',
      priority: 'High',
      categories: ['Due <1h', 'Due 1-4h', 'Due >4h'],
      series: [{ name: 'Open qty', data: [220, 410, 280] }],
      rows: [
        {
          process_order_id: '000147845120',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          open_qty: 240,
          due_time: '2026-05-12T12:30:00Z',
          priority: 'High',
          uom: 'KG',
        },
      ],
    },
  }),
  'wm.inboundReceipts': postQuery({
    key: 'wm.inboundReceipts',
    label: 'Inbound Receipts',
    description: 'Tracks inbound receipt volume, ageing, and execution queue by purchase or STO reference.',
    endpoint: endpoint('wm', 'inbound-receipts'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Inbound quantity', 'number'),
      wmField('points', 'Points', 'array', 'timeseries'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
      wmField('purchase_order_id', 'Purchase order', 'string'),
      wmField('sto_id', 'STO', 'string'),
      wmField('delivery_id', 'Delivery', 'string'),
      wmField('age_minutes', 'Age (minutes)', 'number', 'duration'),
      ...selectFields('material_id', 'material_description', 'batch_id', 'uom'),
    ],
    sampleResponse: {
      value: 6430,
      points: [
        { label: 'Mon', value: 1820 },
        { label: 'Tue', value: 2210 },
        { label: 'Wed', value: 2400 },
      ],
      categories: ['PO receipts', 'STO receipts'],
      series: [{ name: 'Inbound qty', data: [3810, 2620] }],
      rows: [
        {
          purchase_order_id: '4500123456',
          delivery_id: '0080012551',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          batch_id: '0008602411',
          age_minutes: 28,
          uom: 'KG',
        },
      ],
    },
  }),
  'wm.outboundDeliveries': postQuery({
    key: 'wm.outboundDeliveries',
    label: 'Outbound Deliveries',
    description: 'Warehouse execution view of outbound deliveries and their remaining handling quantities.',
    endpoint: endpoint('wm', 'outbound-deliveries'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Outbound quantity', 'number'),
      wmField('points', 'Points', 'array', 'timeseries'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
      wmField('delivery_id', 'Delivery', 'string'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('priority', 'Priority', 'string', 'status'),
      ...selectFields('material_id', 'material_description', 'batch_id', 'uom'),
    ],
    sampleResponse: {
      value: 5120,
      points: [
        { label: 'Mon', value: 1520 },
        { label: 'Tue', value: 1680 },
        { label: 'Wed', value: 1920 },
      ],
      categories: ['Released', 'Picked', 'Loaded'],
      series: [{ name: 'Outbound qty', data: [620, 1880, 2620] }],
      rows: [
        {
          delivery_id: '0080012455',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          batch_id: '0008602411',
          open_qty: 120,
          priority: 'High',
          uom: 'KG',
        },
      ],
    },
  }),
  'wm.binStock': postQuery({
    key: 'wm.binStock',
    label: 'Bin Stock',
    description: 'Stock by warehouse bin, material, and staging status for replenishment and housekeeping decisions.',
    endpoint: endpoint('wm', 'bin-stock'),
    compatibleWidgets: widgetCompatibility.kpiBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Stock quantity', 'number'),
      wmField('storage_type', 'Storage type', 'string'),
      wmField('storage_bin', 'Storage bin', 'string'),
      wmField('staging_status', 'Staging status', 'string', 'status'),
      wmField('rows', 'Rows', 'array'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      ...selectFields('material_id', 'material_description', 'batch_id', 'quantity', 'uom'),
    ],
    sampleResponse: {
      value: 1260,
      storage_type: 'PICK',
      storage_bin: 'P1-02-04',
      staging_status: 'Ready',
      categories: ['PICK', 'BULK', 'STAGE'],
      series: [{ name: 'Stock qty', data: [1260, 3180, 820] }],
      rows: [
        {
          warehouse_number: '061',
          storage_type: 'PICK',
          storage_bin: 'P1-02-04',
          material_id: '000000000020052009',
          material_description: 'Breaded fillet strips 5kg',
          batch_id: '0008602411',
          quantity: 420,
          uom: 'KG',
          staging_status: 'Ready',
        },
      ],
    },
  }),
  'wm.exceptionQueue': postQuery({
    key: 'wm.exceptionQueue',
    label: 'Exception Queue',
    description: 'Highlights blocked, overdue, or exception-driven warehouse work that needs immediate intervention.',
    endpoint: endpoint('wm', 'exception-queue'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Exception count', 'number', 'count'),
      wmField('age_minutes', 'Age (minutes)', 'number', 'duration'),
      wmField('exception_reason', 'Exception reason', 'string', 'status'),
      wmField('points', 'Points', 'array', 'timeseries'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('items', 'Pareto items', 'array'),
      wmField('rows', 'Rows', 'array'),
    ],
    sampleResponse: {
      value: 7,
      age_minutes: 65,
      exception_reason: 'Staging bin blocked',
      points: [
        { label: '06:00', value: 3 },
        { label: '08:00', value: 5 },
        { label: '10:00', value: 7 },
      ],
      categories: ['Blocked bin', 'Missing HU', 'Short pick'],
      series: [{ name: 'Exceptions', data: [3, 2, 2] }],
      items: [
        { label: 'Blocked bin', value: 3 },
        { label: 'Missing HU', value: 2 },
      ],
      rows: [
        {
          process_order_id: '000147845120',
          exception_reason: 'Staging bin blocked',
          age_minutes: 65,
          priority: 'High',
        },
      ],
    },
  }),
  'wm.stagingAging': postQuery({
    key: 'wm.stagingAging',
    label: 'Staging Aging',
    description: 'Measures how long staged stock has been waiting before handoff to production or shipping.',
    endpoint: endpoint('wm', 'staging-aging'),
    compatibleWidgets: widgetCompatibility.kpiTrendBarTable,
    params: wmParams,
    fields: [
      wmField('value', 'Average staging age', 'number', 'duration'),
      wmField('age_minutes', 'Age (minutes)', 'number', 'duration'),
      wmField('points', 'Points', 'array', 'timeseries'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
      wmField('staging_status', 'Staging status', 'string', 'status'),
    ],
    sampleResponse: {
      value: 42,
      age_minutes: 42,
      points: [
        { label: '06:00', value: 36 },
        { label: '08:00', value: 39 },
        { label: '10:00', value: 42 },
      ],
      categories: ['0-30m', '30-60m', '60m+'],
      series: [{ name: 'Staged pallets', data: [6, 4, 2] }],
      rows: [
        {
          warehouse_number: '061',
          process_order_id: '000147845120',
          age_minutes: 42,
          staging_status: 'Ready',
        },
      ],
    },
  }),
  'wm.capacityHotspots': postQuery({
    key: 'wm.capacityHotspots',
    label: 'Capacity Hotspots',
    description: 'Shows the warehouse areas, bins, or work centers with the highest queue pressure or occupancy.',
    endpoint: endpoint('wm', 'capacity-hotspots'),
    compatibleWidgets: widgetCompatibility.barParetoTable,
    params: wmParams,
    fields: [
      wmField('storage_type', 'Storage type', 'string'),
      wmField('storage_bin', 'Storage bin', 'string'),
      wmField('items', 'Pareto items', 'array'),
      wmField('categories', 'Categories', 'array'),
      wmField('series', 'Series', 'array'),
      wmField('rows', 'Rows', 'array'),
      wmField('open_qty', 'Open quantity', 'number'),
      wmField('priority', 'Priority', 'string', 'status'),
    ],
    sampleResponse: {
      categories: ['STAGE-A', 'PICK-01', 'DOCK-03'],
      series: [{ name: 'Open qty', data: [1180, 960, 720] }],
      items: [
        { label: 'STAGE-A', value: 1180 },
        { label: 'PICK-01', value: 960 },
      ],
      rows: [
        {
          storage_type: 'STAGE',
          storage_bin: 'STAGE-A',
          open_qty: 1180,
          priority: 'High',
        },
      ],
    },
  }),
};
