import type { ConnectIOModule, AppComposition } from '@connectio/shared-ui'

export const POH_MODULES: ConnectIOModule[] = [
  {
    moduleId: 'home',
    displayName: 'Home',
    shortName: 'HOME',
    tagline: 'Operations overview',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'home',
    color: 'var(--valentia-slate)',
    sidebarGroup: 'operate',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/',
    i18nNamespace: 'poh.home',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api',
  },
  {
    moduleId: 'poh-orders',
    displayName: 'Process Orders',
    shortName: 'ORDERS',
    tagline: 'Process order list and history',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'history',
    color: 'var(--valentia-slate)',
    sidebarGroup: 'operate',
    sidebarOrder: 1,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Process order management',
      desc: 'Full history of process orders with drill-through to Process Order Detail, quality checks, and yield data.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'In progress' },
        { value: '—', label: 'Completed' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/orders',
    i18nNamespace: 'poh.poh-orders',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api',
  },
  {
    moduleId: 'planning-board',
    displayName: 'Planning',
    shortName: 'PLAN',
    tagline: 'Production planning board',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'calendar',
    color: '#289BA2',
    sidebarGroup: 'operate',
    sidebarOrder: 2,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Planning board',
      desc: 'Line-by-line production schedule with material availability, capacity, and changeover visibility.',
      stats: [
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'Material shorts' },
        { value: '—', label: 'Schedule adherence' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/planning',
    i18nNamespace: 'poh.planning',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'vessel-planning',
    displayName: 'Vessel Planning',
    shortName: 'VESSEL',
    tagline: 'Vessel planning analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'cpu',
    color: '#143700',
    sidebarGroup: 'operate',
    sidebarOrder: 3,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Vessel planning analytics',
      desc: 'Vessel scheduling, utilisation, and changeover analysis across all production lines.',
      stats: [
        { value: '—', label: 'Vessels active' },
        { value: '—', label: 'Utilisation' },
        { value: '—', label: 'Changeovers' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/vessel-planning',
    i18nNamespace: 'poh.vessel-planning',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'pours',
    displayName: 'Pours',
    shortName: 'POURS',
    tagline: 'Pour analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'flask',
    color: '#F24A00',
    sidebarGroup: 'insights',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Pour analytics',
      desc: 'Pour-level throughput, variance, and defect analysis across all lines and shifts.',
      stats: [
        { value: '—', label: 'Pours today' },
        { value: '—', label: 'Defect rate' },
        { value: '—', label: 'OEE' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/pours',
    i18nNamespace: 'poh.pours',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'day-view',
    displayName: 'Day View',
    shortName: 'DAY',
    tagline: 'Day-level operations view',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'clock',
    color: '#289BA2',
    sidebarGroup: 'insights',
    sidebarOrder: 1,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Day-level operations view',
      desc: 'Hour-by-hour production timeline with order status, shift handover context, and line performance for a selected day.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'Lines running' },
        { value: '—', label: 'Shifts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/day-view',
    i18nNamespace: 'poh.day-view',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'yield',
    displayName: 'Yield',
    shortName: 'YIELD',
    tagline: 'Yield analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'trending-up',
    color: '#44CF93',
    sidebarGroup: 'insights',
    sidebarOrder: 2,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Yield analytics',
      desc: 'Material yield by product, line, and shift with variance attribution and trend detection.',
      stats: [
        { value: '—', label: 'Avg yield' },
        { value: '—', label: 'Variance' },
        { value: '—', label: 'Losses' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/yield',
    i18nNamespace: 'poh.yield',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'quality-analytics',
    displayName: 'Quality',
    shortName: 'QA',
    tagline: 'Quality analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'shield',
    color: '#005776',
    sidebarGroup: 'insights',
    sidebarOrder: 3,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality analytics',
      desc: 'In-process quality check results, inspection lot status, and quality-driven order holds across all process orders.',
      stats: [
        { value: '—', label: 'Inspections' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open lots' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/quality',
    i18nNamespace: 'poh.quality',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights',
    displayName: 'Equipment Insights',
    shortName: 'EQUIP',
    tagline: 'Equipment performance insights',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'beaker',
    color: '#289BA2',
    sidebarGroup: 'insights',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment performance insights',
      desc: 'OEE, downtime attribution, and shift-level performance breakdowns for individual pieces of equipment.',
      stats: [
        { value: '—', label: 'Equipment tracked' },
        { value: '—', label: 'Avg OEE' },
        { value: '—', label: 'Downtime events' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/equipment-insights',
    i18nNamespace: 'poh.equipment-insights',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights-2',
    displayName: 'Equipment Estate',
    shortName: 'ESTATE',
    tagline: 'Equipment estate overview',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'activity',
    color: '#289BA2',
    sidebarGroup: 'insights',
    sidebarOrder: 5,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment estate overview',
      desc: 'Four-tab estate view across all equipment — performance, availability, downtime, and trend summaries.',
      stats: [
        { value: '—', label: 'Total equipment' },
        { value: '—', label: 'Active' },
        { value: '—', label: 'Alerts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/equipment-insights-2',
    i18nNamespace: 'poh.equipment-insights-2',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  // order-detail is intentionally absent: it is a parameterized view within poh-orders,
  // not a navigable top-level module. The shell only knows about poh-orders.
]

export const POH_COMPOSITION: AppComposition = {
  appId: 'processorderhistory',
  appDisplayName: 'Process Order History',
  appTagline: 'A Kerry Platform · UAT',
  databricksAppName: 'processorderhistory',
  enabledModules: [
    'home', 'poh-orders', 'planning-board', 'vessel-planning',
    'pours', 'day-view', 'yield', 'quality-analytics', 'equipment-insights', 'equipment-insights-2',
  ],
  mandatoryModules: ['home', 'poh-orders'],
  defaultModule: 'poh-orders',
  sidebarBranding: {
    logoSrc: '/kerry-logo-slate.png',
    logoAlt: 'Kerry',
    appTag: 'Operations',
  },
  sidebarBottomItems: [
    { id: 'platform-home', icon: 'home', iconSet: 'shared-ui', tooltip: 'Platform Home', action: 'external', target: '/' },
  ],
  landingConfig: {
    greetingPrefix: 'GOOD AFTERNOON,',
    operatingConsoleLabel: 'POH · UAT',
    showInbox: false,
    showPlantHealth: false,
    showPinned: false,
    inboxTitle: '',
    plantHealthTitle: '',
    pinnedTitle: '',
  },
  featureFlags: {
    genieEnabled: true,
    darkModeEnabled: false,
  },
  requiredEnvVars: [
    'DATABRICKS_WAREHOUSE_HTTP_PATH',
    'POH_CATALOG',
    'POH_SCHEMA',
    'GENIE_SPACE_ID',
  ],
  backendRouters: [
    'backend.routers.me_router',
    'backend.routers.orders',
    'backend.routers.order_detail_router',
    'backend.routers.pours_router',
    'backend.routers.planning_router',
    'backend.routers.day_view_router',
    'backend.routers.yield_router',
    'backend.routers.quality_router',
    'backend.routers.vessel_planning_router',
    'backend.routers.equipment_insights_router',
    'backend.routers.equipment_insights2_router',
    'backend.routers.genie_router',
  ],
}
