import type { ConnectIOModule } from '@connectio/shared-ui/shell'

export const MODULES: ConnectIOModule[] = [
  // ── Quality Intelligence ──────────────────────────────────────────────────
  {
    moduleId: 'trace',
    displayName: 'Trace',
    shortName: 'TRACE',
    tagline: 'Batch traceability',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'trace',
    color: '#005776',
    sidebarGroup: 'quality',
    sidebarOrder: 1,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Batch traceability · 6 views',
      desc: 'Forward + reverse trace, mass balance, recall readiness, supplier risk and CoA across every batch in the gold layer.',
      stats: [
        { value: '1,284', label: 'Active batches' },
        { value: '3',     label: 'Recall flags',   tone: 'bad' },
        { value: '99.2%', label: 'Trace coverage', tone: 'good' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/cq',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'envmon',
    displayName: 'EnvMon',
    shortName: 'ENVMON',
    tagline: 'Environmental monitoring',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'env',
    color: '#289BA2',
    sidebarGroup: 'quality',
    sidebarOrder: 2,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Environmental monitoring · 4 views',
      desc: 'Spatial heatmaps and time-lapse for MIC inspections, with SPC-driven early warnings and blast-radius vector swabbing.',
      stats: [
        { value: '47', label: 'Sites' },
        { value: '12', label: 'Warnings',   tone: 'warn' },
        { value: '2',  label: 'Open fails', tone: 'bad' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/cq',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'spc',
    displayName: 'SPC',
    shortName: 'SPC',
    tagline: 'Statistical process control',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'spc',
    color: '#F24A00',
    sidebarGroup: 'quality',
    sidebarOrder: 3,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Statistical process control · 5 views',
      desc: 'I-MR, X̄-R, EWMA, CUSUM, P-charts and Hotelling T². Capability indices with confidence intervals, WECO + Nelson rule detection.',
      stats: [
        { value: '318',  label: 'Charts live' },
        { value: '5',    label: 'OOC signals', tone: 'warn' },
        { value: '1.41', label: 'Avg Cpk',     tone: 'good' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/cq',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'lab',
    displayName: 'Lab Board',
    shortName: 'LAB',
    tagline: 'Quality lab wallboard',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'beaker',
    color: '#143C5A',
    sidebarGroup: 'quality',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality lab wallboard',
      desc: 'Live lab results wallboard for in-process quality checks, finished-goods testing, and CoA status across all active batches.',
      stats: [
        { value: '—', label: 'Samples today' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open holds' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/cq',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'enzymes',
    displayName: 'PEX·E·90 Optimiser',
    shortName: 'OPTIM',
    tagline: 'Formula optimisation',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'flask',
    color: '#44CF93',
    sidebarGroup: 'quality',
    sidebarOrder: 5,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Process order formula optimisation',
      desc: 'MILP-based formula optimiser for enzyme production batches. Adjust ingredient constraints, run the solver, compare optimised vs baseline, and accept to SAP.',
      stats: [
        { value: '—', label: 'Active batches' },
        { value: '—', label: 'Avg cost saving' },
        { value: '—', label: 'Solver runs today' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'default',
    routeBase: '/enzymes/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'pex-e-35',
    displayName: 'PEX·E·35 Staging Review',
    shortName: 'PEX35',
    tagline: 'Process order staging review',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'layers',
    color: '#44CF93',
    sidebarGroup: 'quality',
    sidebarOrder: 6,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Process order execution & staging review',
      desc: 'Execution-stage review for PEX-E-35 enzyme batches. Staging status, order progress, quality gate checks, and sign-off readiness across active process orders.',
      stats: [
        { value: '—', label: 'Orders staged' },
        { value: '—', label: 'Gate checks' },
        { value: '—', label: 'Pending sign-off' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/pex-e-35/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },

  // ── Process Operations ────────────────────────────────────────────────────
  {
    moduleId: 'order-list',
    displayName: 'Process Orders',
    shortName: 'ORDERS',
    tagline: 'Process order management',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'archive',
    color: '#005776',
    sidebarGroup: 'operations',
    sidebarOrder: 7,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Process order management',
      desc: 'Full history of process orders with drill-through to Process Order Detail, quality checks, and yield data.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'In progress' },
        { value: '—', label: 'Completed' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'planning-board',
    displayName: 'Planning',
    shortName: 'PLAN',
    tagline: 'Planning board',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'calendar',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 8,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Planning board',
      desc: 'Line-by-line production schedule with material availability, capacity, and changeover visibility.',
      stats: [
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'Material shorts' },
        { value: '—', label: 'Schedule adherence' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'vessel-planning',
    displayName: 'Vessel Planning',
    shortName: 'VESSEL',
    tagline: 'Vessel planning analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'flow',
    color: '#143700',
    sidebarGroup: 'operations',
    sidebarOrder: 9,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Vessel planning analytics',
      desc: 'Vessel scheduling, utilisation, and changeover analysis across all production lines.',
      stats: [
        { value: '—', label: 'Vessels active' },
        { value: '—', label: 'Utilisation' },
        { value: '—', label: 'Changeovers' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'pours',
    displayName: 'Pours',
    shortName: 'POURS',
    tagline: 'Pour analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'activity',
    color: '#F24A00',
    sidebarGroup: 'operations',
    sidebarOrder: 10,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Pour analytics',
      desc: 'Pour-level throughput, variance, and defect analysis across all lines and shifts.',
      stats: [
        { value: '—', label: 'Pours today' },
        { value: '—', label: 'Defect rate' },
        { value: '—', label: 'OEE' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'day-view',
    displayName: 'Day View',
    shortName: 'DAY',
    tagline: 'Day-level operations view',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'clock',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 11,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Day-level operations view',
      desc: 'Hour-by-hour production timeline with order status, shift handover context, and line performance for a selected day.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'Lines running' },
        { value: '—', label: 'Shifts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'yield',
    displayName: 'Yield',
    shortName: 'YIELD',
    tagline: 'Yield analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'bar-chart',
    color: '#44CF93',
    sidebarGroup: 'operations',
    sidebarOrder: 12,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Yield analytics',
      desc: 'Material yield by product, line, and shift with variance attribution and trend detection.',
      stats: [
        { value: '—', label: 'Avg yield' },
        { value: '—', label: 'Variance' },
        { value: '—', label: 'Losses' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'quality-analytics',
    displayName: 'Quality',
    shortName: 'QUAL',
    tagline: 'Quality analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'check-circle',
    color: '#005776',
    sidebarGroup: 'operations',
    sidebarOrder: 13,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality analytics',
      desc: 'In-process quality check results, inspection lot status, and quality-driven order holds across all process orders.',
      stats: [
        { value: '—', label: 'Inspections' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open lots' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights',
    displayName: 'Equipment Insights',
    shortName: 'EQUIP',
    tagline: 'Equipment performance insights',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'cpu',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 14,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment performance insights',
      desc: 'OEE, downtime attribution, and shift-level performance breakdowns for individual pieces of equipment.',
      stats: [
        { value: '—', label: 'Equipment tracked' },
        { value: '—', label: 'Avg OEE' },
        { value: '—', label: 'Downtime events' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights-2',
    displayName: 'Equipment Estate',
    shortName: 'ESTATE',
    tagline: 'Equipment estate overview',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'grid',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 15,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment estate overview',
      desc: 'Four-tab estate view across all equipment — performance, availability, downtime, and trend summaries.',
      stats: [
        { value: '—', label: 'Total equipment' },
        { value: '—', label: 'Active' },
        { value: '—', label: 'Alerts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'pi-sheet',
    displayName: 'Process Execution',
    shortName: 'PI',
    tagline: 'Electronic batch record',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'printer',
    color: '#F9C20A',
    sidebarGroup: 'operations',
    sidebarOrder: 16,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Electronic batch record · operator execution',
      desc: 'Operator-facing tablet UI for real-time batch execution. Step-by-step recipe guidance with tolerance checks, deviation capture, and EBR generation.',
      stats: [
        { value: '—', label: 'Orders in progress' },
        { value: '—', label: 'Steps completed' },
        { value: '—', label: 'Open deviations' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'fullscreen',
    routeBase: '/pi-sheet/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'lineside-monitor',
    displayName: 'Lineside Monitor',
    shortName: 'LINES',
    tagline: 'Production floor wallboard',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'maximize',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 17,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Production floor wallboard · live line status',
      desc: 'Wall-mounted TV display for the production floor. Rotating panels show current order, activity feed, next orders, blocked lines, staging status, and shift plan.',
      stats: [
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'Orders running' },
        { value: '—', label: 'Blocked' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'fullscreen',
    routeBase: '/lineside-monitor/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },

  // ── Warehouse & Supply Chain ──────────────────────────────────────────────
  {
    moduleId: 'process-orders',
    displayName: 'Warehouse Cockpit',
    shortName: 'WH',
    tagline: 'Warehouse operations',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'package',
    color: '#289BA2',
    sidebarGroup: 'warehouse',
    sidebarOrder: 18,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Warehouse operations · transfer requests',
      desc: 'Stock transfer planning and execution across facilities. Create transfer requests, sequence dispatch, track interim inventory states, and audit transactions.',
      stats: [
        { value: '—', label: 'Open TRs' },
        { value: '—', label: 'In transit' },
        { value: '—', label: 'Stock accuracy' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/warehouse360',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'imwm',
    displayName: 'Inventory Cockpit',
    shortName: 'INVENT',
    tagline: 'IM/WM dual-system inventory',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'database',
    color: '#F24A00',
    sidebarGroup: 'warehouse',
    sidebarOrder: 19,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'IM/WM dual-system inventory visibility',
      desc: 'SAP IM and WM reconciliation workbench. Highlights stock discrepancies in real time, prioritises by severity and SLA, and provides aging, ABC/XYZ, and expiry-risk analytics.',
      stats: [
        { value: '—', label: 'IM/WM mismatches' },
        { value: '—', label: 'Expiry at risk' },
        { value: '—', label: 'Slow movers' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/imwm/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'tpm',
    displayName: 'TPM Cockpit',
    shortName: 'TPM',
    tagline: 'Toll processing · 7-stage lifecycle',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'route',
    color: '#005776',
    sidebarGroup: 'warehouse',
    sidebarOrder: 20,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Toll processing · 7-stage lifecycle',
      desc: 'End-to-end toll processing management from STO through manufacturing, quality receipt, and customer fulfilment — with lot-level traceability and exception SLA tracking.',
      stats: [
        { value: '—', label: 'Active lots' },
        { value: '—', label: 'In transit' },
        { value: '—', label: 'P1 exceptions' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/tpm/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'plant-maintenance',
    displayName: 'Plant Maintenance',
    shortName: 'MAINT',
    tagline: 'Maintenance planning & reliability',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'settings',
    color: '#143700',
    sidebarGroup: 'warehouse',
    sidebarOrder: 21,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Maintenance planning · reliability · backlog',
      desc: 'Multi-persona maintenance hub: backlog prioritisation, asset reliability drills (MTBF, downtime trends), work order scheduling, and compliance governance.',
      stats: [
        { value: '—', label: 'Open orders' },
        { value: '—', label: 'Overdue' },
        { value: '—', label: 'MTBF' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/maintenance/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
]
