import type { PlatformModuleRegistration } from './moduleManifest'

export const MODULES: PlatformModuleRegistration[] = [
  // ── Analytics ────────────────────────────────────────────────────────────
  {
    moduleId: 'dashboards',
    displayName: 'Dashboards',
    shortName: 'DASH',
    tagline: 'Composable analytics dashboards',
    domain: 'platform',
    iconSet: 'shared-ui',
    icon: 'grid',
    color: '#289BA2',
    sidebarGroup: 'analytics',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Composable analytics · drag-and-drop',
      desc: 'Build, share, and edit custom dashboards using the shared widget library. Drag-and-drop layout, version history, and per-user sharing.',
      stats: [
        { value: '—', label: 'My dashboards' },
        { value: '—', label: 'Shared with me' },
        { value: '—', label: 'Widgets available' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/dashboards',
  },

  // ── Quality Intelligence ──────────────────────────────────────────────────
  {
    moduleId: 'trace',
    displayName: 'Trace',
    shortName: 'TRACE',
    tagline: 'Batch traceability',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'trace',
    color: '#005776',
    sidebarGroup: 'quality',
    sidebarOrder: 1,
    defaultTab: 'header',
    tabs: [
      { id: 'header',       label: 'Batch Header',          num: '01' },
      { id: 'tree',         label: 'Trace Tree',            num: '02' },
      { id: 'mass-balance', label: 'Mass Balance',          num: '03' },
      { id: 'recall',       label: 'Recall Readiness',      num: '04' },
      { id: 'coa',          label: 'Certificate of Analysis', num: '05' },
      { id: 'compare',      label: 'Batch Compare',         num: '06' },
    ],
    landingCard: {
      tag: 'Batch traceability · 6 views',
      desc: 'Forward + reverse trace, mass balance, recall readiness, supplier risk and CoA across every batch in the gold layer.',
      stats: [
        { value: '1,284', label: 'Active batches' },
        { value: '3',     label: 'Recall flags',   tone: 'bad' },
        { value: '99.2%', label: 'Trace coverage', tone: 'good' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/trace/',
    i18nNamespace: 'trace',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'envmon',
    displayName: 'EnvMon',
    shortName: 'ENVMON',
    tagline: 'Environmental monitoring',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'env',
    color: '#289BA2',
    sidebarGroup: 'quality',
    sidebarOrder: 2,
    defaultTab: 'heatmap',
    tabs: [
      { id: 'heatmap',    label: 'Heatmap',     num: '01' },
      { id: 'time-lapse', label: 'Time Lapse',  num: '02' },
      { id: 'alerts',     label: 'Alerts',      num: '03', pip: true },
      { id: 'swabbing',   label: 'Swab Vectors', num: '04' },
    ],
    landingCard: {
      tag: 'Environmental monitoring · 4 views',
      desc: 'Spatial heatmaps and time-lapse for MIC inspections, with SPC-driven early warnings and blast-radius vector swabbing.',
      stats: [
        { value: '47', label: 'Sites' },
        { value: '12', label: 'Warnings',   tone: 'warn' },
        { value: '2',  label: 'Open fails', tone: 'bad' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/envmon/',
    i18nNamespace: 'envmon',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api/em',
  },
  {
    moduleId: 'spc',
    displayName: 'SPC',
    shortName: 'SPC',
    tagline: 'Statistical process control',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'spc',
    color: '#F24A00',
    sidebarGroup: 'quality',
    sidebarOrder: 3,
    defaultTab: 'charts',
    tabs: [
      { id: 'charts',          label: 'Control Charts',  num: '01' },
      { id: 'alarms',          label: 'Alarms',          num: '02', pip: true },
      { id: 'msa',             label: 'Gauge R&R',       num: '03' },
      { id: 'process-control', label: 'Process Control', num: '04' },
      { id: 'chart-config',    label: 'Chart Config',    num: '05' },
    ],
    landingCard: {
      tag: 'Statistical process control · 5 views',
      desc: 'I-MR, X̄-R, EWMA, CUSUM, P-charts and Hotelling T². Capability indices with confidence intervals, WECO + Nelson rule detection.',
      stats: [
        { value: '318',  label: 'Charts live' },
        { value: '5',    label: 'OOC signals', tone: 'warn' },
        { value: '1.41', label: 'Avg Cpk',     tone: 'good' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/spc/',
    i18nNamespace: 'spc',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api/spc',
  },
  {
    moduleId: 'lab',
    displayName: 'Lab Board',
    shortName: 'LAB',
    tagline: 'Quality lab wallboard',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'beaker',
    color: '#143C5A',
    sidebarGroup: 'quality',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality lab wallboard',
      desc: 'Live lab results wallboard for in-process quality checks, finished-goods testing, and CoA status across all active batches.',
      stats: [
        { value: '—', label: 'Samples today' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open holds' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/cq',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'enzymes',
    category: 'demo',
    displayName: 'PEX·E·90 Optimiser',
    shortName: 'OPTIM',
    tagline: 'Formula optimisation',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'flask',
    color: '#44CF93',
    sidebarGroup: 'quality',
    sidebarOrder: 5,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Demo · Process order formula optimisation',
      desc: 'Static concept demo for enzyme production optimisation. Shows the intended workflow, but is not wired to live order, solver, or SAP acceptance services.',
      stats: [
        { value: '—', label: 'Active batches' },
        { value: '—', label: 'Avg cost saving' },
        { value: '—', label: 'Solver runs today' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'default',
    routeBase: '/enzymes/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'pex-e-35',
    category: 'demo',
    displayName: 'PEX·E·35 Staging Review',
    shortName: 'PEX35',
    tagline: 'Process order staging review',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'layers',
    color: '#44CF93',
    sidebarGroup: 'quality',
    sidebarOrder: 6,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Demo · Process order execution & staging review',
      desc: 'Static concept demo for PEX-E-35 staging review. Shows the intended operational surface, but is not wired to live process order or quality-gate services.',
      stats: [
        { value: '—', label: 'Orders staged' },
        { value: '—', label: 'Gate checks' },
        { value: '—', label: 'Pending sign-off' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/pex-e-35/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },

  {
    moduleId: 'quality-suite',
    category: 'demo',
    displayName: 'Connected Quality',
    shortName: 'CQ',
    tagline: 'Quality execution suite',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'check-circle',
    color: '#143C5A',
    sidebarGroup: 'quality',
    sidebarOrder: 6.2,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Blue Sky · Connected quality execution suite',
      desc: 'Concept demo covering the quality execution layer — inspection queue, batch passport, deviation management, and cross-functional quality modules.',
      stats: [
        { value: '—', label: 'Queue items' },
        { value: '—', label: 'Open deviations' },
        { value: '—', label: 'Passports issued' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/quality-suite/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'traceability-portfolio',
    category: 'demo',
    displayName: 'Food Safety Response',
    shortName: 'FSRC',
    tagline: 'Food safety response centre',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'shield',
    color: '#005776',
    sidebarGroup: 'quality',
    sidebarOrder: 6.4,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Blue Sky · Food safety response centre',
      desc: 'Concept demo for end-to-end recall and food safety response — dependency viewer, hold board, batch passport, recall radar, supplier graph, lineage complexity, and more.',
      stats: [
        { value: '—', label: 'Active incidents' },
        { value: '—', label: 'Holds active' },
        { value: '—', label: 'Supplier alerts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/traceability-portfolio/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'blue-sky-trace',
    category: 'demo',
    displayName: 'Investigation Workspace',
    shortName: 'INVEST',
    tagline: 'Recall investigation workspace',
    domain: 'quality',
    iconSet: 'shared-ui',
    icon: 'git',
    color: '#4FA8C8',
    sidebarGroup: 'quality',
    sidebarOrder: 6.5,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Blue Sky · Recall investigation workspace',
      desc: 'Concept demo for cross-plant recall investigation. Lineage graph, material flow, timeline replay, spatial warehouse map, and exposure matrix — all in one workspace.',
      stats: [
        { value: '1',    label: 'Active case',    tone: 'bad' },
        { value: '17',   label: 'Affected batches' },
        { value: '86%',  label: 'Recall confidence' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/blue-sky-trace/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },

  // ── Process Operations ────────────────────────────────────────────────────
  {
    moduleId: 'poh-orders',
    displayName: 'Process Orders',
    shortName: 'ORDERS',
    tagline: 'Process order management',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'archive',
    color: '#005776',
    sidebarGroup: 'operations',
    sidebarOrder: 7,
    defaultTab: 'orders',
    tabs: [
      { id: 'orders',   label: 'Orders',         num: '01' },
      { id: 'planning', label: 'Planning',        num: '02' },
      { id: 'quality',  label: 'Quality Checks',  num: '03' },
      { id: 'yield',    label: 'Yield',           num: '04' },
      { id: 'day-view', label: 'Day View',        num: '05' },
    ],
    landingCard: {
      tag: 'Process order management',
      desc: 'Full history of process orders with drill-through to Process Order Detail, quality checks, and yield data.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'In progress' },
        { value: '—', label: 'Completed' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: true,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'planning-board',
    displayName: 'Planning',
    shortName: 'PLAN',
    tagline: 'Planning board',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'calendar',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 8,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Planning board',
      desc: 'Line-by-line production schedule with material availability, capacity, and changeover visibility.',
      stats: [
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'Material shorts' },
        { value: '—', label: 'Schedule adherence' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'vessel-planning',
    displayName: 'Vessel Planning',
    shortName: 'VESSEL',
    tagline: 'Vessel planning analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'flow',
    color: '#143700',
    sidebarGroup: 'operations',
    sidebarOrder: 9,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Vessel planning analytics',
      desc: 'Vessel scheduling, utilisation, and changeover analysis across all production lines.',
      stats: [
        { value: '—', label: 'Vessels active' },
        { value: '—', label: 'Utilisation' },
        { value: '—', label: 'Changeovers' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'pours',
    displayName: 'Pours',
    shortName: 'POURS',
    tagline: 'Pour analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'activity',
    color: '#F24A00',
    sidebarGroup: 'operations',
    sidebarOrder: 10,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Pour analytics',
      desc: 'Pour-level throughput, variance, and defect analysis across all lines and shifts.',
      stats: [
        { value: '—', label: 'Pours today' },
        { value: '—', label: 'Defect rate' },
        { value: '—', label: 'OEE' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'day-view',
    displayName: 'Day View',
    shortName: 'DAY',
    tagline: 'Day-level operations view',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'clock',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 11,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Day-level operations view',
      desc: 'Hour-by-hour production timeline with order status, shift handover context, and line performance for a selected day.',
      stats: [
        { value: '—', label: 'Orders today' },
        { value: '—', label: 'Lines running' },
        { value: '—', label: 'Shifts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'yield',
    displayName: 'Yield',
    shortName: 'YIELD',
    tagline: 'Yield analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'bar-chart',
    color: '#44CF93',
    sidebarGroup: 'operations',
    sidebarOrder: 12,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Yield analytics',
      desc: 'Material yield by product, line, and shift with variance attribution and trend detection.',
      stats: [
        { value: '—', label: 'Avg yield' },
        { value: '—', label: 'Variance' },
        { value: '—', label: 'Losses' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'quality-analytics',
    displayName: 'Quality',
    shortName: 'QUAL',
    tagline: 'Quality analytics',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'check-circle',
    color: '#005776',
    sidebarGroup: 'operations',
    sidebarOrder: 13,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality analytics',
      desc: 'In-process quality check results, inspection lot status, and quality-driven order holds across all process orders.',
      stats: [
        { value: '—', label: 'Inspections' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open lots' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights',
    displayName: 'Equipment Insights',
    shortName: 'EQUIP',
    tagline: 'Equipment performance insights',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'cpu',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 14,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment performance insights',
      desc: 'OEE, downtime attribution, and shift-level performance breakdowns for individual pieces of equipment.',
      stats: [
        { value: '—', label: 'Equipment tracked' },
        { value: '—', label: 'Avg OEE' },
        { value: '—', label: 'Downtime events' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'equipment-insights-2',
    displayName: 'Equipment Estate',
    shortName: 'ESTATE',
    tagline: 'Equipment estate overview',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'grid',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 15,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Equipment estate overview',
      desc: 'Four-tab estate view across all equipment — performance, availability, downtime, and trend summaries.',
      stats: [
        { value: '—', label: 'Total equipment' },
        { value: '—', label: 'Active' },
        { value: '—', label: 'Alerts' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },
  {
    moduleId: 'pi-sheet',
    category: 'demo',
    displayName: 'Process Execution',
    shortName: 'PI',
    tagline: 'Electronic batch record',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'printer',
    color: '#F9C20A',
    sidebarGroup: 'operations',
    sidebarOrder: 16,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Demo · Electronic batch record · operator execution',
      desc: 'Static concept demo for operator batch execution. Shows the intended tablet workflow, but is not wired to live recipe, deviation, or EBR services.',
      stats: [
        { value: '—', label: 'Orders in progress' },
        { value: '—', label: 'Steps completed' },
        { value: '—', label: 'Open deviations' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'fullscreen',
    routeBase: '/pi-sheet/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'lineside-monitor',
    displayName: 'Lineside Monitor',
    shortName: 'LINES',
    tagline: 'Production floor wallboard',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'maximize',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 17,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Production floor wallboard · live line status',
      desc: 'Wall-mounted TV display for the production floor. Rotating panels show current order, activity feed, next orders, blocked lines, staging status, and shift plan.',
      stats: [
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'Orders running' },
        { value: '—', label: 'Blocked' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/poh',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api',
  },

  {
    moduleId: 'operations-suite',
    category: 'demo',
    displayName: 'Operations Suite',
    shortName: 'OPS',
    tagline: 'Operations decision layer',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'activity',
    color: '#F24A00',
    sidebarGroup: 'operations',
    sidebarOrder: 17.5,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Blue Sky · Operations decision layer',
      desc: 'Concept demo covering the full operations surface — inbox, changeover, flow, lineside, OEE, adherence, equipment, ageing, rhythm, handover, and daily production actions.',
      stats: [
        { value: '—', label: 'Open actions' },
        { value: '—', label: 'Lines running' },
        { value: '—', label: 'Schedule adherence' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/operations-suite/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'factory-mood-board',
    category: 'demo',
    displayName: 'Plant Mood Board',
    shortName: 'MOOD',
    tagline: 'Plant-level mood assessment',
    domain: 'process-order',
    iconSet: 'shared-ui',
    icon: 'bar-chart',
    color: '#289BA2',
    sidebarGroup: 'operations',
    sidebarOrder: 17.8,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Blue Sky · Plant mood board',
      desc: 'AI-synthesised plant state assessment — OEE trend, downtime pulse, quality yield, blocked stock pressure, equipment health, and narrative insights in one board.',
      stats: [
        { value: '—', label: 'Plant mood' },
        { value: '—', label: 'OEE today' },
        { value: '—', label: 'Signals in band' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/factory-mood-board/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },

  // ── Warehouse & Supply Chain ──────────────────────────────────────────────
  {
    moduleId: 'wh-cockpit',
    displayName: 'Warehouse Cockpit',
    shortName: 'WH',
    tagline: 'Warehouse operations',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'package',
    color: '#289BA2',
    sidebarGroup: 'warehouse',
    sidebarOrder: 18,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Warehouse operations · transfer requests',
      desc: 'Stock transfer planning and execution across facilities. Create transfer requests, sequence dispatch, track interim inventory states, and audit transactions.',
      stats: [
        { value: '—', label: 'Open TRs' },
        { value: '—', label: 'In transit' },
        { value: '—', label: 'Stock accuracy' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/warehouse360',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'imwm',
    displayName: 'Inventory Cockpit',
    shortName: 'INVENT',
    tagline: 'IM/WM dual-system inventory',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'database',
    color: '#F24A00',
    sidebarGroup: 'warehouse',
    sidebarOrder: 19,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'IM/WM dual-system inventory visibility',
      desc: 'SAP IM and WM reconciliation workbench. Highlights stock discrepancies in real time, prioritises by severity and SLA, and provides aging, ABC/XYZ, and expiry-risk analytics.',
      stats: [
        { value: '—', label: 'IM/WM mismatches' },
        { value: '—', label: 'Expiry at risk' },
        { value: '—', label: 'Slow movers' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/warehouse360',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'tpm',
    category: 'demo',
    displayName: 'TPM Cockpit',
    shortName: 'TPM',
    tagline: 'Toll processing · 7-stage lifecycle',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'route',
    color: '#005776',
    sidebarGroup: 'warehouse',
    sidebarOrder: 20,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Demo · Toll processing · 7-stage lifecycle',
      desc: 'Static concept demo for toll processing. Shows the intended lifecycle, but is not wired to live STO, lot traceability, fulfilment, or exception services.',
      stats: [
        { value: '—', label: 'Active lots' },
        { value: '—', label: 'In transit' },
        { value: '—', label: 'P1 exceptions' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/tpm/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
  {
    moduleId: 'plant-maintenance',
    category: 'demo',
    displayName: 'Plant Maintenance',
    shortName: 'MAINT',
    tagline: 'Maintenance planning & reliability',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'settings',
    color: '#143700',
    sidebarGroup: 'warehouse',
    sidebarOrder: 21,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Demo · Maintenance planning · reliability · backlog',
      desc: 'Static concept demo for plant maintenance. Shows the intended backlog and reliability workflows, but is not wired to live work order or asset services.',
      stats: [
        { value: '—', label: 'Open orders' },
        { value: '—', label: 'Overdue' },
        { value: '—', label: 'MTBF' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/maintenance/',
    i18nNamespace: 'platform',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '',
  },
]
