import type { ConnectIOModule, AppComposition } from '@connectio/shared-ui'

export const W360_MODULES: ConnectIOModule[] = [
  {
    moduleId: 'home',
    displayName: 'Home',
    shortName: 'HOME',
    tagline: 'Warehouse control tower',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'home',
    color: 'var(--valentia-slate)',
    sidebarGroup: 'main',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/',
    i18nNamespace: 'w360.home',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'process-orders',
    displayName: 'Production Staging',
    shortName: 'STAGING',
    tagline: 'Production staging and orders',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'layers',
    color: '#005776',
    sidebarGroup: 'main',
    sidebarOrder: 1,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Production staging',
      desc: 'Order staging, line assignment, and material pick management for the shift.',
      stats: [
        { value: '—', label: 'Orders staged' },
        { value: '—', label: 'Lines active' },
        { value: '—', label: 'At risk' },
      ],
    },
    contextBarSlot: true,
    routeBase: '/staging',
    i18nNamespace: 'w360.process-orders',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'deliveries',
    displayName: 'Deliveries',
    shortName: 'DELIV',
    tagline: 'Outbound deliveries',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'package',
    color: '#289BA2',
    sidebarGroup: 'main',
    sidebarOrder: 2,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/deliveries',
    i18nNamespace: 'w360.deliveries',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'inbound',
    displayName: 'Inbound',
    shortName: 'INBND',
    tagline: 'Inbound receipts',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'download',
    color: '#44CF93',
    sidebarGroup: 'main',
    sidebarOrder: 3,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/inbound',
    i18nNamespace: 'w360.inbound',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'inventory',
    displayName: 'Inventory',
    shortName: 'INV',
    tagline: 'Inventory management',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'database',
    color: '#143700',
    sidebarGroup: 'main',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/inventory',
    i18nNamespace: 'w360.inventory',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'dispensary',
    displayName: 'Dispensary',
    shortName: 'DISP',
    tagline: 'Ingredient dispensary',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'flask',
    color: '#F24A00',
    sidebarGroup: 'main',
    sidebarOrder: 5,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/dispensary',
    i18nNamespace: 'w360.dispensary',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'exceptions',
    displayName: 'Exceptions',
    shortName: 'EXC',
    tagline: 'Exception management',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'alert-triangle',
    color: '#ef4444',
    sidebarGroup: 'main',
    sidebarOrder: 6,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/exceptions',
    i18nNamespace: 'w360.exceptions',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
  {
    moduleId: 'performance',
    displayName: 'Performance',
    shortName: 'PERF',
    tagline: 'Performance analytics',
    domain: 'warehouse',
    iconSet: 'shared-ui',
    icon: 'trending-up',
    color: '#8b5cf6',
    sidebarGroup: 'main',
    sidebarOrder: 7,
    defaultTab: '',
    tabs: [],
    contextBarSlot: true,
    routeBase: '/performance',
    i18nNamespace: 'w360.performance',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/wh',
  },
]

export const W360_COMPOSITION: AppComposition = {
  appId: 'warehouse360',
  appDisplayName: 'Warehouse360',
  appTagline: 'A Kerry Platform · UAT',
  databricksAppName: 'warehouse360',
  enabledModules: [
    'home',
    'process-orders',
    'deliveries',
    'inbound',
    'inventory',
    'dispensary',
    'exceptions',
    'performance',
  ],
  mandatoryModules: ['home'],
  defaultModule: 'home',
  sidebarBranding: {
    logoSrc: '/kerry-logo-slate.png',
    logoAlt: 'Kerry',
    appTag: 'Warehouse',
  },
  sidebarBottomItems: [],
  landingConfig: {
    greetingPrefix: 'GOOD AFTERNOON,',
    operatingConsoleLabel: 'W360 · UAT',
    showInbox: false,
    showPlantHealth: false,
    showPinned: false,
    inboxTitle: '',
    plantHealthTitle: '',
    pinnedTitle: '',
  },
  featureFlags: {
    genieEnabled: false,
    darkModeEnabled: false,
  },
  requiredEnvVars: ['DATABRICKS_WAREHOUSE_HTTP_PATH'],
  backendRouters: [
    'backend.routers.process_orders',
    'backend.routers.deliveries',
    'backend.routers.inbound',
    'backend.routers.inventory',
    'backend.routers.dispensary',
    'backend.routers.kpis',
    'backend.routers.plants',
  ],
}
