[app]
name = "warehouse360"
bundle_name = "warehouse360"
default_profile = "uat"
default_target = "uat"
template = "app.template.yaml"
config_output = "app.yaml"

[build]
cwd = "."
command = "python3 scripts/build.py"

[bundle]
include_target = true

[post_deploy]
enabled = true
source_target = "target"
repair_sql_scope = false

[targets.uat.env]
DATABRICKS_WAREHOUSE_ID = "e76480b94bea6ed5"
DATABRICKS_WAREHOUSE_HTTP_PATH = "/sql/1.0/warehouses/e76480b94bea6ed5"
TRACE_CATALOG = "connected_plant_uat"
TRACE_SCHEMA = "wh360"

[targets.prod.env]
DATABRICKS_WAREHOUSE_ID = ""
DATABRICKS_WAREHOUSE_HTTP_PATH = ""
TRACE_CATALOG = ""
TRACE_SCHEMA = "wh360"
