/**
 * Genie Conversation API client for the platform app.
 *
 * Implements the multi-space contract: every request carries moduleId so the
 * backend can route to the correct Genie space, and spaceId is threaded on
 * follow-up / polling calls to pin the conversation to its origin space.
 */

/**
 * Ephemeral page context passed to Genie with every message.
 *
 * This context allows the Genie assistant to understand what the user is currently
 * looking at in the platform UI (e.g., a specific process order or material).
 */
export interface PlatformGenieContext {
  /** The ID of the currently selected process order, if any. */
  selected_process_order?: string | null
  /** The ID of the currently selected material, if any. */
  selected_material?: string | null
  /** The ID of the currently selected plant, if any. */
  selected_plant?: string | null
  /** The ID of the currently selected batch, if any. */
  selected_batch?: string | null
  /** The active date range in the UI (e.g., "today", "last-30-days"). */
  active_date_range?: string | null
  /** A JSON string of any active filters applied to the view. */
  active_filters?: string | null
  /** The number of rows currently shown in the active data table. */
  selected_row_count?: number | null
}

/**
 * An attachment returned by Genie, such as a SQL query or a text block.
 */
export interface GenieAttachment {
  /** The unique ID for this attachment, used to fetch query results. */
  attachmentId: string | null
  /** Optional text content associated with the attachment. */
  text: string | null
  /** Optional SQL query generated by Genie for this attachment. */
  sql: string | null
  /** The type of attachment (e.g., "sql", "text"). */
  type?: string | null
}

/**
 * The response from a Genie message request (start or follow-up).
 */
export interface GenieMessageResponse {
  /** The ID of the current conversation. */
  conversationId: string | null
  /** The unique ID of this specific message. */
  messageId: string | null
  /**
   * The Space ID returned by /genie/start.
   * This must be stored and resent on all subsequent follow-up and polling calls
   * to ensure the backend routes to the correct domain-aligned space.
   */
  spaceId?: string
  /** The current status of the message (e.g., "IN_PROGRESS", "COMPLETED"). */
  status: string | null
  /** An error object if the Genie request failed. */
  error?: unknown
  /** The text answer generated by Genie. */
  answer: string
  /** A list of attachments (e.g., SQL queries) generated by Genie. */
  attachments: GenieAttachment[]
}

/**
 * The structured result of a Genie query attachment.
 */
export interface GenieQueryResult {
  /** The names of the columns in the result set. */
  columns: string[]
  /** The data rows returned by the query. */
  rows: Record<string, unknown>[]
  /** The raw result object from the backend. */
  raw: unknown
}

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { credentials: 'include' })
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText)
    throw new Error(`Genie API ${res.status}: ${text}`)
  }
  return res.json() as Promise<T>
}

async function postJson<T>(url: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText)
    throw new Error(`Genie API ${res.status}: ${text}`)
  }
  return res.json() as Promise<T>
}

/** Start a new Genie conversation routed to the correct space for moduleId. */
export function startGenieConversation(
  prompt: string,
  pageContext: PlatformGenieContext,
  moduleId: string,
): Promise<GenieMessageResponse> {
  return postJson<GenieMessageResponse>('/api/genie/start', { prompt, pageContext, moduleId })
}

/** Send a follow-up message, pinning the conversation to its origin spaceId. */
export function sendGenieFollowup(
  conversationId: string,
  spaceId: string,
  prompt: string,
  pageContext: PlatformGenieContext,
  moduleId: string,
): Promise<GenieMessageResponse> {
  return postJson<GenieMessageResponse>('/api/genie/followup', {
    conversationId,
    spaceId,
    prompt,
    pageContext,
    moduleId,
  })
}

/** Poll a Genie message for its completion status. */
export function fetchGenieMessage(
  conversationId: string,
  messageId: string,
  spaceId: string,
  moduleId: string,
): Promise<GenieMessageResponse> {
  const params = new URLSearchParams({ conversationId, messageId, spaceId, moduleId })
  return getJson<GenieMessageResponse>(`/api/genie/message?${params}`)
}

/** Fetch structured query results for a Genie attachment. */
export function fetchGenieQueryResult(
  conversationId: string,
  messageId: string,
  attachmentId: string,
  spaceId: string,
  moduleId: string,
): Promise<GenieQueryResult> {
  const params = new URLSearchParams({ conversationId, messageId, attachmentId, spaceId, moduleId })
  return getJson<GenieQueryResult>(`/api/genie/query-result?${params}`)
}
