#!/usr/bin/env python3
"""Generate read-only consolidation drift reports for the monorepo."""

from __future__ import annotations

import ast
import json
import re
import tomllib
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
APPS_DIR = ROOT / "apps"
REPORT_DIR = ROOT / "reports" / "consolidation"

HTTP_METHODS = ("get", "post", "put", "patch", "delete")
ROUTE_RE = re.compile(r"@router\.(?P<method>get|post|put|patch|delete)\(\s*['\"](?P<path>[^'\"]+)['\"]")
RATE_LIMIT_RE = re.compile(r"@limiter\.limit\(\s*['\"](?P<limit>[^'\"]+)['\"]")
TABLE_RE = re.compile(
    r"""
    tbl\(\s*['"](?P<tbl>[A-Za-z0-9_.$-]+)['"]\s*\)
    |['"](?P<quoted>\b(?:gold|silver|bronze|spc|em)_[A-Za-z0-9_.$-]+\b)['"]
    """,
    re.VERBOSE,
)
FETCH_RE = re.compile(r"\bfetch\s*\(\s*['\"](?P<path>/api/[^'\"]+)['\"]")
CLIENT_PATH_RE = re.compile(r"['\"](?P<path>/api/[^'\"]+)['\"]")


@dataclass(frozen=True)
class Route:
    app: str
    method: str
    path: str
    module: str
    handler: str
    line: int
    rate_limit: str
    freshness_sources: tuple[str, ...]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def app_dirs() -> list[Path]:
    return sorted(path for path in APPS_DIR.iterdir() if path.is_dir())


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(read_text(path))


def load_toml(path: Path) -> dict[str, Any]:
    return tomllib.loads(read_text(path))


def markdown_table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(cell).replace("\n", "<br>") for cell in row) + " |")
    return "\n".join(lines)


def first_function_after(lines: list[str], index: int) -> tuple[str, int]:
    for offset in range(index, min(len(lines), index + 8)):
        stripped = lines[offset].strip()
        if stripped.startswith("async def ") or stripped.startswith("def "):
            name = stripped.split("def ", 1)[1].split("(", 1)[0]
            return name, offset + 1
    return "unknown", index + 1


def freshness_sources_near(lines: list[str], index: int) -> tuple[str, ...]:
    end = min(len(lines), index + 120)
    for offset in range(index + 1, end):
        if ROUTE_RE.search(lines[offset]):
            end = offset
            break
    window = "\n".join(lines[index:end])
    if "attach_payload_freshness" not in window:
        return ()
    return tuple(sorted(set(re.findall(r"['\"](gold_[A-Za-z0-9_]+|em_[A-Za-z0-9_]+|spc_[A-Za-z0-9_]+)['\"]", window))))


def scan_routes() -> list[Route]:
    routes: list[Route] = []
    for app_dir in app_dirs():
        backend = app_dir / "backend"
        if not backend.exists():
            continue
        for path in sorted(backend.rglob("*.py")):
            lines = read_text(path).splitlines()
            for index, line in enumerate(lines):
                match = ROUTE_RE.search(line)
                if not match:
                    continue
                rate_limit = ""
                for nearby in range(max(0, index - 3), min(len(lines), index + 4)):
                    rate_match = RATE_LIMIT_RE.search(lines[nearby])
                    if rate_match:
                        rate_limit = rate_match.group("limit")
                handler, handler_line = first_function_after(lines, index + 1)
                routes.append(
                    Route(
                        app=app_dir.name,
                        method=match.group("method").upper(),
                        path=match.group("path"),
                        module=rel(path),
                        handler=handler,
                        line=handler_line,
                        rate_limit=rate_limit or "-",
                        freshness_sources=freshness_sources_near(lines, index),
                    )
                )
    return routes


def report_routes(routes: list[Route]) -> str:
    rows = [
        [
            route.app,
            route.method,
            route.path,
            f"{route.module}:{route.line}",
            route.handler,
            route.rate_limit,
            ", ".join(route.freshness_sources) or "-",
        ]
        for route in routes
    ]
    by_app = Counter(route.app for route in routes)
    summary_rows = [[app, count] for app, count in sorted(by_app.items())]
    return "\n\n".join(
        [
            "# Backend Route Map",
            "Generated by `scripts/consolidation_audit.py`.",
            "## Summary",
            markdown_table(["App", "Route count"], summary_rows),
            "## Routes",
            markdown_table(
                ["App", "Method", "Path", "Handler location", "Handler", "Rate limit", "Freshness sources"],
                rows,
            ),
            "",
        ]
    )


def source_files_for_sql() -> list[Path]:
    suffixes = {".py", ".sql", ".sh", ".yaml", ".yml", ".toml", ".md"}
    files: list[Path] = []
    for base in [ROOT / "apps", ROOT / "libs", ROOT / "scripts"]:
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.is_file() and (path.suffix in suffixes or path.name == "Makefile"):
                if ".venv" not in path.parts and "node_modules" not in path.parts:
                    files.append(path)
    return sorted(files)


def scan_sql_tables() -> dict[str, dict[str, Counter[str]]]:
    app_tables: dict[str, dict[str, Counter[str]]] = defaultdict(lambda: defaultdict(Counter))
    for path in source_files_for_sql():
        text = read_text(path)
        owner = "repo"
        parts = path.relative_to(ROOT).parts
        if len(parts) >= 2 and parts[0] == "apps":
            owner = parts[1]
        for line_number, line in enumerate(text.splitlines(), start=1):
            for match in TABLE_RE.finditer(line):
                table = match.group("tbl") or match.group("quoted")
                if table and len(table) > 3:
                    app_tables[owner][table][f"{rel(path)}:{line_number}"] += 1
    return app_tables


def report_sql_tables(app_tables: dict[str, dict[str, Counter[str]]]) -> str:
    rows: list[list[str]] = []
    for owner in sorted(app_tables):
        for table in sorted(app_tables[owner]):
            locations = app_tables[owner][table]
            sample_locations = sorted(locations)[:6]
            rows.append([owner, table, sum(locations.values()), "<br>".join(sample_locations)])
    shared = defaultdict(set)
    for owner, tables in app_tables.items():
        for table in tables:
            shared[table].add(owner)
    shared_rows = [
        [table, ", ".join(sorted(owners))]
        for table, owners in sorted(shared.items())
        if len(owners) > 1 and "repo" not in owners
    ]
    return "\n\n".join(
        [
            "# SQL Table Reference Map",
            "Generated by `scripts/consolidation_audit.py`.",
            "## Shared References",
            markdown_table(["Table or view", "Apps"], shared_rows),
            "## All References",
            markdown_table(["Owner", "Table or view", "Mentions", "Sample locations"], rows),
            "",
        ]
    )


def dependency_sections() -> dict[str, dict[str, str]]:
    sections: dict[str, dict[str, str]] = {}
    for app_dir in app_dirs():
        package = app_dir / "frontend" / "package.json"
        if package.exists():
            data = load_json(package)
            deps: dict[str, str] = {}
            for key in ("dependencies", "devDependencies"):
                for name, version in data.get(key, {}).items():
                    deps[name] = str(version)
            sections[f"{app_dir.name}/frontend"] = deps
        for pyproject in sorted(app_dir.glob("**/pyproject.toml")):
            data = load_toml(pyproject)
            project = data.get("project", {})
            deps = {}
            for item in project.get("dependencies", []):
                name = re.split(r"[<>=!~;\[]", item, maxsplit=1)[0].strip()
                deps[name] = item
            for group_name, group_deps in data.get("dependency-groups", {}).items():
                for item in group_deps:
                    name = re.split(r"[<>=!~;\[]", item, maxsplit=1)[0].strip()
                    deps[f"{group_name}:{name}"] = item
            sections[rel(pyproject).removesuffix("/pyproject.toml")] = deps
    for lib_project in sorted((ROOT / "libs").glob("*/pyproject.toml")):
        data = load_toml(lib_project)
        deps = {}
        for item in data.get("project", {}).get("dependencies", []):
            name = re.split(r"[<>=!~;\[]", item, maxsplit=1)[0].strip()
            deps[name] = item
        sections[rel(lib_project).removesuffix("/pyproject.toml")] = deps
    return sections


def report_dependencies(sections: dict[str, dict[str, str]]) -> str:
    all_names = sorted({name for deps in sections.values() for name in deps})
    drift_rows: list[list[str]] = []
    for name in all_names:
        versions = {owner: deps[name] for owner, deps in sections.items() if name in deps}
        distinct = sorted(set(versions.values()))
        if len(versions) > 1 and len(distinct) > 1:
            drift_rows.append([name, "<br>".join(f"{owner}: `{version}`" for owner, version in sorted(versions.items()))])
    matrix_rows = [
        [owner, len(deps), ", ".join(sorted(deps)[:18]) + (" ..." if len(deps) > 18 else "")]
        for owner, deps in sorted(sections.items())
    ]
    return "\n\n".join(
        [
            "# Dependency Drift Report",
            "Generated by `scripts/consolidation_audit.py`.",
            "## Version Drift",
            markdown_table(["Dependency", "Versions"], drift_rows),
            "## Dependency Sets",
            markdown_table(["Package", "Dependency count", "Sample dependencies"], matrix_rows),
            "",
        ]
    )


def deploy_stage_flags(app_dir: Path) -> dict[str, str]:
    files = [
        app_dir / "Makefile",
        app_dir / "deploy.sh",
        app_dir / "deploy.toml",
        app_dir / "databricks.yml",
        app_dir / "app.template.yaml",
    ]
    scripts_dir = app_dir / "scripts"
    if scripts_dir.exists():
        files.extend(sorted(scripts_dir.rglob("*.sh")))
    combined = "\n".join(read_text(path) for path in files if path.exists())
    template = read_text(app_dir / "app.template.yaml") if (app_dir / "app.template.yaml").exists() else ""
    databricks = read_text(app_dir / "databricks.yml") if (app_dir / "databricks.yml").exists() else ""
    manifest = read_text(app_dir / "deploy.toml") if (app_dir / "deploy.toml").exists() else ""
    uses_shared_wrapper = "deploy_app.py" in combined and bool(manifest)
    post_deploy_enabled = "enabled = true" in manifest and "[post_deploy]" in manifest
    return {
        "shared wrapper": "yes" if uses_shared_wrapper else "no",
        "auth check": "yes" if "current-user me" in combined or uses_shared_wrapper else "no",
        "frontend build": "yes" if "npm run build" in combined else "no",
        "render app config": "yes" if "app.template.yaml" in combined or "envsubst" in combined else "no",
        "bundle deploy": "yes" if "bundle deploy" in combined or uses_shared_wrapper else "no",
        "post deploy": "yes" if "post-deploy" in combined or "apps deploy" in combined or post_deploy_enabled else "no",
        "scope handling": "yes"
        if "user_api_scopes" in combined
        or "user_api_scopes" in databricks
        or "repair_sql_scope = true" in manifest
        else "no",
        "migration hooks": "yes" if "[[migrations]]" in manifest or "after_bundle" in manifest else "no",
        "cli pin": "yes" if "databricks_cli_version" in databricks else "no",
        "template syntax": "${VAR}" if "${" in template else "$VAR" if "$" in template else "-",
    }


def report_deploy_drift() -> str:
    rows: list[list[str]] = []
    for app_dir in app_dirs():
        flags = deploy_stage_flags(app_dir)
        rows.append(
            [
                app_dir.name,
                flags["shared wrapper"],
                flags["auth check"],
                flags["frontend build"],
                flags["render app config"],
                flags["bundle deploy"],
                flags["post deploy"],
                flags["scope handling"],
                flags["migration hooks"],
                flags["cli pin"],
                flags["template syntax"],
            ]
        )
    return "\n\n".join(
        [
            "# Deployment Drift Report",
            "Generated by `scripts/consolidation_audit.py`.",
            "Trace2 is treated as the reference baseline because it has the proven end-to-end deploy flow.",
            markdown_table(
                [
                    "App",
                    "Shared wrapper",
                    "Auth check",
                    "Frontend build",
                    "Render config",
                    "Bundle deploy",
                    "Post deploy",
                    "Scope handling",
                    "Migration hooks",
                    "CLI pin",
                    "Template syntax",
                ],
                rows,
            ),
            "",
        ]
    )


def test_counts() -> Counter[str]:
    counts: Counter[str] = Counter()
    for app_dir in app_dirs():
        for path in app_dir.rglob("*"):
            if not path.is_file():
                continue
            if "node_modules" in path.parts or ".venv" in path.parts:
                continue
            is_py_test = path.name.startswith("test_") and path.suffix == ".py"
            is_ts_test = path.suffix in {".ts", ".tsx"} and (".test." in path.name or ".spec." in path.name)
            if not (is_py_test or is_ts_test):
                continue
            layer = "frontend" if "frontend" in path.parts else "backend" if "backend" in path.parts else "other"
            counts[f"{app_dir.name}/{layer}"] += 1
    return counts


def report_test_matrix() -> str:
    counts = test_counts()
    rows = []
    for app_dir in app_dirs():
        rows.append(
            [
                app_dir.name,
                counts.get(f"{app_dir.name}/backend", 0),
                counts.get(f"{app_dir.name}/frontend", 0),
                counts.get(f"{app_dir.name}/other", 0),
            ]
        )
    gaps = []
    for app, backend, frontend, _other in rows:
        if int(backend) == 0:
            gaps.append(f"{app}: no backend tests detected")
        if int(frontend) == 0:
            gaps.append(f"{app}: no frontend tests detected")
    return "\n\n".join(
        [
            "# Test Coverage Matrix",
            "Generated by `scripts/consolidation_audit.py`.",
            markdown_table(["App", "Backend tests", "Frontend tests", "Other tests"], rows),
            "## Gaps",
            "\n".join(f"- {gap}" for gap in gaps) if gaps else "- No obvious test-count gaps detected.",
            "",
        ]
    )


def scan_frontend_api() -> str:
    rows: list[list[str]] = []
    for app_dir in app_dirs():
        frontend = app_dir / "frontend" / "src"
        if not frontend.exists():
            continue
        for path in sorted(frontend.rglob("*")):
            if path.suffix not in {".ts", ".tsx", ".js", ".jsx"}:
                continue
            text = read_text(path)
            endpoints = sorted(set(CLIENT_PATH_RE.findall(text)))
            if not endpoints and "fetch(" not in text and "ApiError" not in text and "useQuery" not in text:
                continue
            rows.append(
                [
                    app_dir.name,
                    rel(path),
                    ", ".join(endpoints) or "-",
                    "yes" if "ApiError" in text else "no",
                    "yes" if "useQuery" in text or "useMutation" in text else "no",
                    text.count("fetch("),
                ]
            )
    return "\n\n".join(
        [
            "# Frontend API Call Map",
            "Generated by `scripts/consolidation_audit.py`.",
            markdown_table(
                ["App", "File", "API paths", "ApiError", "React Query", "fetch calls"],
                rows,
            ),
            "",
        ]
    )


def write_report(filename: str, content: str) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    (REPORT_DIR / filename).write_text(content, encoding="utf-8")


def main() -> None:
    routes = scan_routes()
    write_report("route-map.md", report_routes(routes))
    write_report("sql-table-map.md", report_sql_tables(scan_sql_tables()))
    write_report("dependency-drift.md", report_dependencies(dependency_sections()))
    write_report("deploy-drift.md", report_deploy_drift())
    write_report("test-matrix.md", report_test_matrix())
    write_report("frontend-api-map.md", scan_frontend_api())
    print(f"Wrote consolidation reports to {rel(REPORT_DIR)}")


if __name__ == "__main__":
    main()
