import type { ConnectIOModule, AppComposition } from '@connectio/shared-ui'

export const CQ_MODULES: ConnectIOModule[] = [
  {
    moduleId: 'home',
    displayName: 'Home',
    shortName: 'HOME',
    tagline: 'Cross-module overview',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'home',
    color: 'var(--valentia-slate)',
    sidebarGroup: 'main',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/',
    i18nNamespace: 'cq.home',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'lab',
    displayName: 'Lab Board',
    shortName: 'LAB',
    tagline: 'Quality lab wallboard',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'target',
    color: '#143C5A',
    sidebarGroup: 'main',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    landingCard: {
      tag: 'Quality lab wallboard',
      desc: 'Live lab results wallboard for in-process quality checks, finished-goods testing, and CoA status across all active batches.',
      stats: [
        { value: '—', label: 'Samples today' },
        { value: '—', label: 'Pass rate' },
        { value: '—', label: 'Open holds' },
      ],
    },
    contextBarSlot: false,
    layoutMode: 'fullscreen',
    routeBase: '/lab',
    i18nNamespace: 'cq.lab',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'alarms',
    displayName: 'Alarms',
    shortName: 'ALARMS',
    tagline: 'Cross-module inbox',
    domain: 'platform',
    iconSet: 'cq',
    icon: 'bell',
    color: 'var(--sunset)',
    sidebarGroup: 'platform',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/alarms',
    i18nNamespace: 'cq.alarms',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'admin',
    displayName: 'Settings',
    shortName: 'ADMIN',
    tagline: 'Admin',
    domain: 'platform',
    iconSet: 'cq',
    icon: 'settings',
    color: 'var(--cq-fg-3)',
    sidebarGroup: 'admin',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/admin',
    i18nNamespace: 'cq.admin',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
]

export const CQ_COMPOSITION: AppComposition = {
  appId: 'connectedquality',
  appDisplayName: 'ConnectedQuality',
  appTagline: 'A Kerry Platform · UAT',
  databricksAppName: 'connectedquality',
  enabledModules: ['home', 'lab', 'alarms', 'admin'],
  mandatoryModules: ['home', 'alarms', 'admin'],
  defaultModule: 'home',
  sidebarBranding: {
    appTag: 'Quality',
  },
  sidebarBottomItems: [
    { id: 'platform-home', icon: 'home', iconSet: 'cq', tooltip: 'Platform Home', action: 'external', target: '/' },
    { id: 'help', icon: 'help',     iconSet: 'cq', tooltip: 'Help',     action: 'modal',    target: 'help' },
    { id: 'user', icon: 'user',     iconSet: 'cq', tooltip: 'User',     action: 'navigate', target: 'admin' },
  ],
  landingConfig: {
    greetingPrefix: 'GOOD AFTERNOON,',
    operatingConsoleLabel: 'Operating console',
    showInbox: true,
    showPlantHealth: true,
    showPinned: true,
    inboxTitle: 'Cross-module inbox',
    plantHealthTitle: 'Plant health',
    pinnedTitle: 'Pinned views',
  },
  featureFlags: {
    genieEnabled: false,
    darkModeEnabled: true,
  },
  requiredEnvVars: [
    'DATABRICKS_WAREHOUSE_HTTP_PATH',
    'TRACE_CATALOG',
    'TRACE_SCHEMA',
  ],
  backendRouters: [
    'backend.routers.lab',
    'backend.routers.alarms',
  ],
}
