import type { ConnectIOModule, AppComposition } from '@connectio/shared-ui'

export const CQ_MODULES: ConnectIOModule[] = [
  {
    moduleId: 'home',
    displayName: 'Home',
    shortName: 'HOME',
    tagline: 'Cross-module overview',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'home',
    color: 'var(--valentia-slate)',
    sidebarGroup: 'main',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/',
    i18nNamespace: 'cq.home',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'trace',
    displayName: 'Trace',
    shortName: 'TRACE',
    tagline: 'Batch traceability',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'trace',
    color: '#005776',
    sidebarGroup: 'main',
    sidebarOrder: 1,
    defaultTab: 'overview',
    tabs: [
      { id: 'overview',     label: 'Overview',         num: '01' },
      { id: 'recall',       label: 'Recall Readiness', num: '02', pip: true },
      { id: 'lineage',      label: 'Lineage',          num: '03' },
      { id: 'mass_balance', label: 'Mass Balance',     num: '04' },
      { id: 'quality',      label: 'Quality',          num: '05' },
      { id: 'coa',          label: 'CoA',              num: '06' },
    ],
    landingCard: {
      tag: 'Batch traceability · 6 views',
      desc: 'Forward + reverse trace, mass balance, recall readiness, supplier risk and CoA across every batch in the gold layer.',
      stats: [
        { value: '1,284', label: 'Active batches' },
        { value: '3',     label: 'Recall flags',   tone: 'bad' },
        { value: '99.2%', label: 'Trace coverage', tone: 'good' },
      ],
    },
    contextBarSlot: true,
    routeBase: '/trace',
    i18nNamespace: 'cq.trace',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'envmon',
    displayName: 'EnvMon',
    shortName: 'ENVMON',
    tagline: 'Environmental monitoring',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'env',
    color: '#289BA2',
    sidebarGroup: 'main',
    sidebarOrder: 2,
    defaultTab: 'global',
    tabs: [
      { id: 'global',  label: 'Global Map', num: '01' },
      { id: 'site',    label: 'Site',       num: '02' },
      { id: 'floor',   label: 'Floor Plan', num: '03', pip: true },
      { id: 'history', label: 'Time-Lapse', num: '04' },
    ],
    landingCard: {
      tag: 'Environmental monitoring · 4 views',
      desc: 'Spatial heatmaps and time-lapse for MIC inspections, with SPC-driven early warnings and blast-radius vector swabbing.',
      stats: [
        { value: '47', label: 'Sites' },
        { value: '12', label: 'Warnings',   tone: 'warn' },
        { value: '2',  label: 'Open fails', tone: 'bad' },
      ],
    },
    contextBarSlot: false,
    routeBase: '/envmon',
    i18nNamespace: 'cq.envmon',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'spc',
    displayName: 'SPC',
    shortName: 'SPC',
    tagline: 'Statistical process control',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'spc',
    color: '#F24A00',
    sidebarGroup: 'main',
    sidebarOrder: 3,
    defaultTab: 'overview',
    tabs: [
      { id: 'overview',  label: 'Overview',       num: '01' },
      { id: 'flow',      label: 'Process Flow',   num: '02' },
      { id: 'charts',    label: 'Control Charts', num: '03', pip: true },
      { id: 'scorecard', label: 'Scorecard',      num: '04' },
      { id: 'advanced',  label: 'Multivariate',   num: '05' },
    ],
    landingCard: {
      tag: 'Statistical process control · 5 views',
      desc: 'I-MR, X̄-R, EWMA, CUSUM, P-charts and Hotelling T². Capability indices with confidence intervals, WECO + Nelson rule detection.',
      stats: [
        { value: '318',  label: 'Charts live' },
        { value: '5',    label: 'OOC signals', tone: 'warn' },
        { value: '1.41', label: 'Avg Cpk',     tone: 'good' },
      ],
    },
    contextBarSlot: true,
    routeBase: '/spc',
    i18nNamespace: 'cq.spc',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'lab',
    displayName: 'Lab Board',
    shortName: 'LAB',
    tagline: 'Quality lab wallboard',
    domain: 'quality',
    iconSet: 'cq',
    icon: 'target',
    color: '#143C5A',
    sidebarGroup: 'main',
    sidebarOrder: 4,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    layoutMode: 'fullscreen',
    routeBase: '/lab',
    i18nNamespace: 'cq.lab',
    isUserSelectable: true,
    isPinnedByDefault: false,
    isMandatory: false,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'alarms',
    displayName: 'Alarms',
    shortName: 'ALARMS',
    tagline: 'Cross-module inbox',
    domain: 'platform',
    iconSet: 'cq',
    icon: 'bell',
    color: 'var(--sunset)',
    sidebarGroup: 'platform',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/alarms',
    i18nNamespace: 'cq.alarms',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
  {
    moduleId: 'admin',
    displayName: 'Settings',
    shortName: 'ADMIN',
    tagline: 'Admin',
    domain: 'platform',
    iconSet: 'cq',
    icon: 'settings',
    color: 'var(--cq-fg-3)',
    sidebarGroup: 'admin',
    sidebarOrder: 0,
    defaultTab: '',
    tabs: [],
    contextBarSlot: false,
    routeBase: '/admin',
    i18nNamespace: 'cq.admin',
    isUserSelectable: false,
    isPinnedByDefault: false,
    isMandatory: true,
    backendPrefix: '/api/cq',
  },
]

export const CQ_COMPOSITION: AppComposition = {
  appId: 'connectedquality',
  appDisplayName: 'ConnectedQuality',
  appTagline: 'A Kerry Platform · UAT',
  databricksAppName: 'connectedquality',
  enabledModules: ['home', 'trace', 'envmon', 'spc', 'lab', 'alarms', 'admin'],
  mandatoryModules: ['home', 'alarms', 'admin'],
  defaultModule: 'home',
  sidebarBranding: {
    appTag: 'Quality',
  },
  sidebarBottomItems: [
    { id: 'help', icon: 'help',     iconSet: 'cq', tooltip: 'Help',     action: 'modal',    target: 'help' },
    { id: 'user', icon: 'user',     iconSet: 'cq', tooltip: 'User',     action: 'navigate', target: 'admin' },
  ],
  landingConfig: {
    greetingPrefix: 'GOOD AFTERNOON,',
    operatingConsoleLabel: 'Operating console',
    showInbox: true,
    showPlantHealth: true,
    showPinned: true,
    inboxTitle: 'Cross-module inbox',
    plantHealthTitle: 'Plant health',
    pinnedTitle: 'Pinned views',
  },
  featureFlags: {
    genieEnabled: false,
    darkModeEnabled: true,
  },
  requiredEnvVars: [
    'DATABRICKS_WAREHOUSE_HTTP_PATH',
    'TRACE_CATALOG',
    'TRACE_SCHEMA',
  ],
  backendRouters: [
    'backend.routers.trace',
    'backend.routers.envmon',
    'backend.routers.spc',
    'backend.routers.lab',
    'backend.routers.alarms',
  ],
}
